# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import commands_pb2 as commands__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in commands_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Access = channel.unary_unary(
                '/Commands/Access',
                request_serializer=commands__pb2.CommandRequest.SerializeToString,
                response_deserializer=commands__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Add = channel.unary_unary(
                '/Commands/Add',
                request_serializer=commands__pb2.CommandRequest.SerializeToString,
                response_deserializer=commands__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/Commands/Remove',
                request_serializer=commands__pb2.CommandRequest.SerializeToString,
                response_deserializer=commands__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/Commands/Get',
                request_serializer=commands__pb2.CommandRequest.SerializeToString,
                response_deserializer=commands__pb2.CommandReply.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/Commands/List',
                request_serializer=commands__pb2.CommandRequest.SerializeToString,
                response_deserializer=commands__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/Commands/Mkdir',
                request_serializer=commands__pb2.CommandRequest.SerializeToString,
                response_deserializer=commands__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Rmdir = channel.unary_unary(
                '/Commands/Rmdir',
                request_serializer=commands__pb2.CommandRequest.SerializeToString,
                response_deserializer=commands__pb2.CommandReply.FromString,
                _registered_method=True)


class CommandsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Access(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rmdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Access': grpc.unary_unary_rpc_method_handler(
                    servicer.Access,
                    request_deserializer=commands__pb2.CommandRequest.FromString,
                    response_serializer=commands__pb2.CommandReply.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=commands__pb2.CommandRequest.FromString,
                    response_serializer=commands__pb2.CommandReply.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=commands__pb2.CommandRequest.FromString,
                    response_serializer=commands__pb2.CommandReply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=commands__pb2.CommandRequest.FromString,
                    response_serializer=commands__pb2.CommandReply.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=commands__pb2.CommandRequest.FromString,
                    response_serializer=commands__pb2.CommandReply.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=commands__pb2.CommandRequest.FromString,
                    response_serializer=commands__pb2.CommandReply.SerializeToString,
            ),
            'Rmdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Rmdir,
                    request_deserializer=commands__pb2.CommandRequest.FromString,
                    response_serializer=commands__pb2.CommandReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Commands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Commands', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Commands(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Access(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Commands/Access',
            commands__pb2.CommandRequest.SerializeToString,
            commands__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Commands/Add',
            commands__pb2.CommandRequest.SerializeToString,
            commands__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Commands/Remove',
            commands__pb2.CommandRequest.SerializeToString,
            commands__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Commands/Get',
            commands__pb2.CommandRequest.SerializeToString,
            commands__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Commands/List',
            commands__pb2.CommandRequest.SerializeToString,
            commands__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Commands/Mkdir',
            commands__pb2.CommandRequest.SerializeToString,
            commands__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rmdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Commands/Rmdir',
            commands__pb2.CommandRequest.SerializeToString,
            commands__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
