# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commands.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\"#\n\x0e\x43ommandRequest\x12\x11\n\tparameter\x18\x01 \x01(\t\"\x1f\n\x0c\x43ommandReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa6\x02\n\x08\x43ommands\x12(\n\x06\x41\x63\x63\x65ss\x12\x0f.CommandRequest\x1a\r.CommandReply\x12%\n\x03\x41\x64\x64\x12\x0f.CommandRequest\x1a\r.CommandReply\x12(\n\x06Remove\x12\x0f.CommandRequest\x1a\r.CommandReply\x12%\n\x03Get\x12\x0f.CommandRequest\x1a\r.CommandReply\x12&\n\x04List\x12\x0f.CommandRequest\x1a\r.CommandReply\x12\'\n\x05Mkdir\x12\x0f.CommandRequest\x1a\r.CommandReply\x12\'\n\x05Rmdir\x12\x0f.CommandRequest\x1a\r.CommandReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=18
  _globals['_COMMANDREQUEST']._serialized_end=53
  _globals['_COMMANDREPLY']._serialized_start=55
  _globals['_COMMANDREPLY']._serialized_end=86
  _globals['_COMMANDS']._serialized_start=89
  _globals['_COMMANDS']._serialized_end=383
# @@protoc_insertion_point(module_scope)
